#!/usr/bin/env bash
# script to install nginx

apt-get -y update
apt-get -y install nginx
mkdir -p /var/www/html
chown -R "$USER":"$USER"  /var/www/html/
echo "Hello World!" > /var/www/html/index.html

if [[ $(pgrep nginx) ]]
then
	sudo service nginx restart
else
	sudo service nginx start
fi

