#!/usr/bin/env bash
# script to install nginx
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
