#!/usr/bin/env bash
# 0. Nginx likes port 80. Script to debug container to listen to port 80
sudo service nginx stop
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx start
